### PR TITLE
Completed Template Matching Tutorial

### LINKED ISSUE #19: Implement a system that can identify a single hero from a single image using template matching

### PR DESCRIPTION
**Pull request by sanasc**
Template matching tutorial. Prints out the score for the template matched against every "patch" in the source image. Currently uses a true sample (Mercy want) and a false sample (Soldier gun).

### CODE REVIEW

**Review by mmunson2 — APPROVED** [review]
Looks great! Appreciate the README.

**Review by DaviidK — CHANGES_REQUESTED** [review]
We should probably add some light documentation to our tutorials. Definitely not as in-depth as for our programming assignments, but maybe a header and a quick description & pre/post conditions for methods?

Otherwise it looks great!

**Review by lalinw — APPROVED** [review]
Looks good! Good call on the .gitignore changes as well.

**Review by DaviidK — APPROVED** [review]
Looking good! Think that's all clear for merging

**Pull request merged**
